const videosDatabase = {
  stockmarket: [
    `Xt-jFF6dlgk`,
    `jbNi7aXEcJk`,
    `21Pm9MB6kOk`,
    `iWBjHPFrwrM`,
    `Gz07wOEk8YQ`,
    `96KM562jyKI`,
    `ctYaB_e4Lb0`,
    `hBKqk5oYexw`,
    `LRgWGsrzMAU`,
    `KR_U_X039_k`,
    `Us03mJPU_lc`,
    `C406ZRad9VQ`,
    `5CWrpR6mcFw`,
    `oq5U-mRJ61w`,
    `DP7rr1zMuj8`,
    `A9kiXS_gB0k`,
    `4MjCdCIFFis`,
    `VBQutFk3Lac`,
    `_1Ptl5R8FXQ`,
    `dl0ovMB4Pqw`,
    `8RPTn7ZBsG8`,
    `01GRBpGBKCw`,
    `krwSDbuHWd4`,
    `vN-IuTnwLOo1`,
    `VirdoEdqoaw1`,
    `VmS50W38fKc1`,
    `MwITkemCnp41`,
    `zQZOThvodTM`,
    `iX8rk7YgZY0`,
  ],
  mutualfunds: [`LOVjaw5G-2g`, `zmTDHl161pw`],
  gold: [`CM3hLxpvD-c`, `WDypUuRJdJs`, `olJqTa2vzkM`],
  smallcase: [`E0kTiBHkabQ`],
  scams: [
    `1FRJoJfLX7k`,
    `_-kQ_dtiY6I`,
    `zRTmbP83K38`,
    `OfDu8nnCqTk`,
    `T5GL6Yb5Cxw`,
    `UtKLFZ-dvF8`,
  ],
  businesscasestudies: [
    `rSOraWGMX48`,
    `j35e6PhOMJU`,
    `vR7nDyyqvWc`,
    `2Pkpu3ogIgQ`,
    `yhpVAki47RI`,
    `xKEtVu_k9jQ`,
    `31UVvKEYO6k`,
    `6-tS7-IhCbI`,
    `EdpoEmifW7M`,
    `JqSeQ3c4_qI`,
  ],
  investmentstrategies: [
    `TLGalocqj00`,
    `Luj3L8x4uwo`,
    `tN3ZtnswCWI`,
    `_DYuHz9VBLo`,
    `1DRq8N7SpYc`,
  ],
  crypto: [`HaYupvyjJxI`, `e0frvHLHMGI`, `PdduvP_KlcI`, `pm6Xz-iHpgw`],
  nfts: [`wOqJzJri8B0`, `peUF5SyBXJE`, `as7acW3B2jA`],
  books: [`dxledVtSAt4`],
};

module.exports = { videosDatabase };
